chore: add Lighthouse CI

diff --git a/.github/workflows/lighthouse-ci.yml b/.github/workflows/lighthouse-ci.yml
--- a/.github/workflows/lighthouse-ci.yml
+++ b/.github/workflows/lighthouse-ci.yml
@@ -1,13 +1,12 @@
-name: "🚀 build and commit"
-
+name: Build project and run Lighthouse CI
 on:
   push:
     branches:
       - main
 
 jobs:
-  build:
-    name: workflow
+  lhci:
+    name: Lighthouse CI
     runs-on: ubuntu-latest
     steps:
       - name: 📚 checkout
@@ -19,10 +18,7 @@ jobs:
           registry-url: https://registry.npmjs.org
       - name: ⬇️ download dependencies
         run: npm ci
-      - name: 🛠 build project
-        run: npm run build
-      - name: 🚀 commit and push
-        uses: stefanzweifel/git-auto-commit-action@v4
-        with:
-          commit_message: "chore: build files"
-          file_pattern: docs/*
+      - name: 🏎 lighthouse CI
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
